"""empty message

Revision ID: 167c1c505fd5
Revises: 
Create Date: 2022-06-19 16:25:58.324612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167c1c505fd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sex', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sex')
    # ### end Alembic commands ###
